### ISSUE TITLE
Spinner not spinning after booting from the hibernation mode

### ISSUE THREAD

**Issue by iamaakashbasnet** [farsil/monoarch#2]
When turning on my laptop and booting, the spinner spins and when turning off my laptop the arch logo glows. But when I wake my laptop from hibernation mode it shows the spinner but it doesn't spin. How can we fix this issue?

**Comment by farsil** [comment]
Hello, I'm afraid I don't use and maintain this repository anymore. If you can fix the issue, you are encouraged to fork this repository and update the relevant [AUR package](https://aur.archlinux.org/packages/plymouth-theme-monoarch) yourself.

I'm more than glad to relinquish ownership, and happy that is still being used by someone :)
